import { Inter } from "next/font/google";
import "./globals.css";
import getServerDarkMode from "@/hooks/use-server-dark-mode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

// Có thay đổi về hàm getServerDarkMode vì lỗi await
export default async function RootLayout({ children }) {
  const theme = await getServerDarkMode();
  return (
    <html lang="en" className={theme}>
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
